version: "3.8"
services:
  frontend:
    build:
      context: ./filmlingo_fe
      dockerfile: Dockerfile
    env_file:
      - ./filmlingo_fe/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./filmlingo_be
      dockerfile: Dockerfile
    env_file:
      - ./filmlingo_be/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: filmlingo_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
